"""Workflow template rendering (spec 03 §2, §6).

Templates live at the repo root in `workflow-templates/`, not inside the
backend package, because they are a separately-released deliverable: they ship
*into* customer repos and are versioned independently of the service that
renders them (spec 03 §6).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from mykronos.adapters.registry import default_tool

#: Every rendered file carries this. It is how the installer tells a file it
#: generated from one a human wrote at the same path (spec 03 §8) — which is
#: the difference between an update and silently destroying someone's work.
GENERATED_MARKER = "Generated by Mykronos Workflow Installer"


class TemplateError(RuntimeError):
    """A template is missing, malformed, or referenced a value we did not supply."""


@dataclass(frozen=True)
class TemplateSpec:
    capability: str
    template: str
    target: str
    version: str
    summary: str = ""


@dataclass(frozen=True)
class RenderedWorkflow:
    capability: str
    path: str
    content: str
    version: str


def _build_environment(directory: Path) -> Environment:
    """Jinja with remapped variable delimiters.

    GitHub Actions expressions are `${{ ... }}`; Jinja's default variable
    syntax is `{{ ... }}`. Left alone, Jinja tries to evaluate every Actions
    expression in the file. Remapping variables to `<< >>` keeps the templates
    readable as workflows instead of burying them in `{% raw %}` blocks.

    Block and comment syntax keep their defaults, and an earlier version of
    this docstring claimed neither collides. Comment syntax does: bash's
    array-length expansion — dollar, brace, hash — opens a Jinja comment that
    never closes, and the template fails to compile with "Missing end of
    comment tag" pointing at a line well past the real one.

    Remapping comments too would be the tidy fix and is not worth it: every
    existing `{# ... #}` block in every template would start rendering into
    the output. The templates avoid the sequence instead, and
    `test_adapters_phase2` fails if one reintroduces it.

    `StrictUndefined` makes a missing render variable an error rather than an
    empty string, so a typo produces a failed install instead of a workflow
    that silently posts to nowhere.
    """
    return Environment(
        loader=FileSystemLoader(directory),
        variable_start_string="<<",
        variable_end_string=">>",
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=False,
        lstrip_blocks=False,
        autoescape=False,  # YAML, not HTML — escaping would corrupt it.
    )


class TemplateLibrary:
    """Loads `manifest.json` and renders capability workflows from it."""

    def __init__(self, directory: Path) -> None:
        self.directory = directory
        self._manifest_path = directory / "manifest.json"
        if not self._manifest_path.is_file():
            raise TemplateError(
                f"No template manifest at {self._manifest_path}. "
                "The Workflow Installer cannot render anything without it."
            )
        raw = json.loads(self._manifest_path.read_text(encoding="utf-8"))
        self.specs: dict[str, TemplateSpec] = {
            capability: TemplateSpec(
                capability=capability,
                template=entry["template"],
                target=entry["target"],
                version=entry["version"],
                summary=entry.get("summary", ""),
            )
            for capability, entry in raw.get("templates", {}).items()
        }
        self._env = _build_environment(directory)

    @property
    def available(self) -> set[str]:
        return set(self.specs)

    def spec(self, capability: str) -> TemplateSpec:
        try:
            return self.specs[capability]
        except KeyError:
            raise TemplateError(
                f"No workflow template for capability '{capability}'. "
                f"Available: {', '.join(sorted(self.specs)) or 'none'}."
            ) from None

    def target_path(self, capability: str) -> str:
        return self.spec(capability).target

    def render(
        self,
        capability: str,
        *,
        repo_full_name: str,
        default_branch: str,
        ingestion_api_url: str,
        token_secret_name: str,
        upload_action_ref: str,
        config: dict[str, Any] | None = None,
        **extra: Any,
    ) -> RenderedWorkflow:
        """Render one capability's workflow for one repo."""
        spec = self.spec(capability)
        template = self._env.get_template(spec.template)

        context: dict[str, Any] = {
            "capability": capability,
            # The tool the rendered workflow declares to the upload action when
            # config names none. It has to come from the adapter registry: the
            # previous default was the capability name, which is not a tool for
            # any capability, so every unconfigured workflow uploaded under a
            # label no adapter could resolve.
            "default_tool": default_tool(capability),
            "template_version": spec.version,
            "repo_full_name": repo_full_name,
            "default_branch": default_branch,
            "ingestion_api_url": ingestion_api_url.rstrip("/"),
            "token_secret_name": token_secret_name,
            "upload_action_ref": upload_action_ref,
            # The ref half of `upload_action_ref`, passed to the action so the
            # package it installs matches the action itself.
            #
            # This was tried twice at runtime and failed twice. First as a
            # hardcoded `v0.1.0` default on the action, a tag that never
            # existed. Then as `github.action_ref`, which is empty inside a
            # composite action — so every scan failed at upload with a loud
            # error instead of a quiet one. Resolving it here ends the guessing:
            # the ref in the `uses:` line and the ref the package installs from
            # are now the same string, computed once, at render time.
            "mykronos_ref": upload_action_ref.rpartition("@")[2] or "main",
            "config": config or {},
            # CodeQL needs an explicit language matrix; the config may override.
            "languages": (config or {}).get("languages") or ["javascript-typescript", "python"],
            # The Oracle gate waits on these before deciding (spec 09 §8).
            # Rendered from the repo's *enabled* capabilities, so the gate
            # never waits for a scanner that will never run -- a workflow_run
            # trigger naming an absent workflow simply never fires, and the
            # gate would silently stop producing decisions.
            "gate_depends_on": extra.pop("gate_depends_on", []),
        }
        context.update(extra)

        content = template.render(**context)
        if GENERATED_MARKER not in content:
            # A template without the marker would be indistinguishable from a
            # hand-written file on the next install, and the collision check
            # (spec 03 §8) would refuse to touch it forever.
            raise TemplateError(
                f"Template '{spec.template}' does not emit the generated-file marker. "
                f"Every rendered workflow must contain: {GENERATED_MARKER!r}"
            )

        return RenderedWorkflow(
            capability=capability, path=spec.target, content=content, version=spec.version
        )


def is_mykronos_generated(content: str | None) -> bool:
    """Whether a file at one of our target paths is ours to overwrite."""
    return content is not None and GENERATED_MARKER in content
