"""Workflow Installer — spec 03.

The interesting behaviour is all in the edges: what happens on a repeated
save, on a half-finished PR, and when a human already owns the path we want.

Two libraries are in play. `installer` uses the real shipped templates, for
assertions about the actual rendered SAST workflow. `multi` uses a synthetic
two-capability library, because the installer's diffing and idempotency logic
is inherently multi-capability while Phase 1 ships exactly one template —
testing that against a fixture means these tests keep asserting the same thing
when Phase 2 adds five more.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterator

import pytest
from sqlalchemy.orm import Session

from mykronos.auth import TokenRegistry
from mykronos.config import get_settings
from mykronos.db import Database
from mykronos.db.models import Organization, RepoOnboarding, WorkflowInstallEvent
from mykronos.github import FakeGitHubClient
from mykronos.installer import (
    BRANCH_PREFIX,
    DEFAULT_SECRET_NAME,
    GENERATED_MARKER,
    InstallerError,
    PathCollisionError,
    TemplateLibrary,
    WorkflowInstaller,
)
from mykronos.installer.installer import _gate_depends_on

REPO = "example-org/payments-api"
SAST_PATH = ".github/workflows/mykronos-sast.yml"
SECRETS_PATH = ".github/workflows/mykronos-secrets.yml"

GENERIC_TEMPLATE = (
    "# Generated by Mykronos Workflow Installer - template version: "
    "<< template_version >>\n"
    "name: Mykronos << capability >>\n"
    "on: [pull_request]\n"
    "jobs:\n"
    "  scan:\n"
    "    runs-on: ubuntu-latest\n"
    "    steps:\n"
    "      - uses: << upload_action_ref >>\n"
    "        with:\n"
    "          token: ${{ secrets.<< token_secret_name >> }}\n"
)


@pytest.fixture
def session(tmp_path) -> Iterator[Session]:
    db = Database(f"sqlite:///{(tmp_path / 'installer.db').as_posix()}")
    db.create_all()
    with db.session() as s:
        yield s
    db.close()


@pytest.fixture
def onboarding(session: Session) -> RepoOnboarding:
    org = Organization(github_org_login="example-org")
    session.add(org)
    session.flush()
    row = RepoOnboarding(
        org_id=org.id,
        github_repo_full_name=REPO,
        github_installation_id=4242,
        status="pending_install",
        enabled_capabilities=[],
        default_branch="main",
        onboarded_by="tgb",
    )
    session.add(row)
    session.flush()
    return row


@pytest.fixture
def github() -> FakeGitHubClient:
    client = FakeGitHubClient()
    client.add_repo(REPO, files={"README.md": "# payments"})
    return client


@pytest.fixture
def installer(github: FakeGitHubClient) -> WorkflowInstaller:
    """Over the real shipped template library."""
    return WorkflowInstaller(
        github,
        TemplateLibrary(get_settings().workflow_templates_dir),
        ingestion_api_url="https://mykronos.internal",
        upload_action_ref="ToddGBenson/mykronos/actions/upload-results@v1",
    )


@pytest.fixture
def multi(github: FakeGitHubClient, tmp_path) -> WorkflowInstaller:
    """Over a synthetic library with two capabilities."""
    directory = tmp_path / "templates"
    directory.mkdir()
    manifest = {
        "templates": {
            "sast": {
                "template": "generic.yml.j2",
                "target": SAST_PATH,
                "version": "1.0.0",
                "summary": "Static analysis",
            },
            "secrets": {
                "template": "generic.yml.j2",
                "target": SECRETS_PATH,
                "version": "1.0.0",
                "summary": "Secret detection",
            },
        }
    }
    (directory / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
    (directory / "generic.yml.j2").write_text(GENERIC_TEMPLATE, encoding="utf-8")

    return WorkflowInstaller(
        github,
        TemplateLibrary(directory),
        ingestion_api_url="https://mykronos.internal",
        upload_action_ref="ToddGBenson/mykronos/actions/upload-results@v1",
    )


@pytest.fixture
def registry(session: Session) -> TokenRegistry:
    return TokenRegistry(session)


async def install(installer, session, onboarding, registry, capabilities: set[str]):
    plan = await installer.plan(onboarding, capabilities)
    return await installer.apply(session, onboarding, plan, actor="tgb", registry=registry)


async def already_enabled(
    installer: WorkflowInstaller,
    github: FakeGitHubClient,
    onboarding: RepoOnboarding,
    *capabilities: str,
    config: dict[str, dict[str, object]] | None = None,
) -> None:
    """Put the repo in the state a merged install PR would leave it in.

    Setting `enabled_capabilities` alone is not that state — it says the
    workflow is running while the file it would run from is absent. The
    installer compares rendered content against the repository now, so a
    fixture that skips the file makes "already enabled" and "never installed"
    indistinguishable, and every no-op test passes for the wrong reason.
    """
    onboarding.enabled_capabilities = sorted(capabilities)
    repo = github.repos[onboarding.github_repo_full_name]
    for capability in capabilities:
        rendered = installer.templates.render(
            capability,
            repo_full_name=onboarding.github_repo_full_name,
            default_branch=onboarding.default_branch,
            ingestion_api_url=installer.ingestion_api_url,
            token_secret_name=installer.secret_name,
            upload_action_ref=installer.upload_action_ref,
            mykronos_package_spec=installer.package_spec,
            config=(config or {}).get(capability, {}),
            gate_depends_on=_gate_depends_on(capability, sorted(capabilities)),
        )
        repo.files[rendered.path] = rendered.content
        repo.branches[repo.default_branch][rendered.path] = rendered.content


class TestPlanning:
    async def test_enabling_a_capability_stages_its_workflow(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding
    ) -> None:
        plan = await installer.plan(onboarding, {"sast"})
        assert plan.added == ["sast"]
        assert [c.path for c in plan.changes] == [SAST_PATH]
        assert GENERATED_MARKER in (plan.changes[0].content or "")

    async def test_disabling_stages_a_deletion(
        self,
        installer: WorkflowInstaller,
        onboarding: RepoOnboarding,
        github: FakeGitHubClient,
    ) -> None:
        """spec 03 §3.3: default is to delete the file so the repo's Actions
        tab stays clean."""
        await already_enabled(installer, github, onboarding, "sast")
        plan = await installer.plan(onboarding, set())
        assert plan.removed == ["sast"]
        assert plan.changes[0].is_delete

    async def test_a_deletion_is_not_staged_for_a_file_that_is_gone(
        self,
        installer: WorkflowInstaller,
        onboarding: RepoOnboarding,
    ) -> None:
        """Somebody deleted the workflow by hand before disabling it here.
        Committing a deletion for a path that does not exist is a commit that
        changes nothing, and on GitHub it is an error rather than a no-op."""
        onboarding.enabled_capabilities = ["sast"]
        plan = await installer.plan(onboarding, set())
        assert plan.removed == ["sast"]
        assert plan.changes == []
        assert plan.is_noop

    async def test_requesting_the_current_set_is_a_noop(
        self,
        installer: WorkflowInstaller,
        onboarding: RepoOnboarding,
        github: FakeGitHubClient,
    ) -> None:
        """spec 03 §4: no duplicate PR on a repeated save."""
        await already_enabled(installer, github, onboarding, "sast")
        plan = await installer.plan(onboarding, {"sast"})
        assert plan.is_noop
        assert plan.changes == []

    async def test_a_config_change_alone_is_not_a_noop(
        self,
        installer: WorkflowInstaller,
        onboarding: RepoOnboarding,
        github: FakeGitHubClient,
    ) -> None:
        """The bug this replaced. `sast` stays enabled and the capability set
        does not move, so the old set-comparison returned "nothing to do" —
        while the new language matrix sat in the database, disagreeing with a
        repository nobody had told."""
        await already_enabled(installer, github, onboarding, "sast")

        plan = await installer.plan(
            onboarding, {"sast"}, configs={"sast": {"languages": ["python"]}}
        )

        assert not plan.is_noop
        assert plan.updated == ["sast"]
        assert plan.added == []
        assert [c.path for c in plan.changes] == [SAST_PATH]
        assert '["python"]' in (plan.changes[0].content or "")

    async def test_an_unchanged_config_is_still_a_noop(
        self,
        installer: WorkflowInstaller,
        onboarding: RepoOnboarding,
        github: FakeGitHubClient,
    ) -> None:
        """The other half. Re-saving identical config must not push a
        byte-identical diff, which is churn on somebody's open pull request."""
        config = {"sast": {"languages": ["python"]}}
        await already_enabled(installer, github, onboarding, "sast", config=config)

        plan = await installer.plan(onboarding, {"sast"}, configs=config)

        assert plan.is_noop
        assert plan.updated == []

    async def test_unknown_capability_is_refused(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding
    ) -> None:
        with pytest.raises(InstallerError, match="No workflow template"):
            await installer.plan(onboarding, {"telepathy"})

    async def test_rendered_workflow_carries_repo_context(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding
    ) -> None:
        plan = await installer.plan(onboarding, {"sast"})
        content = plan.changes[0].content or ""
        assert REPO in content
        assert "https://mykronos.internal/api/ingest/health" in content
        assert DEFAULT_SECRET_NAME in content
        # Version-agnostic: the marker must be stamped, but pinning the number
        # here would make every template bump a test failure.
        assert re.search(r"template version: \d+\.\d+\.\d+", content)

    async def test_capability_config_reaches_the_template(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding
    ) -> None:
        plan = await installer.plan(
            onboarding,
            {"sast"},
            configs={"sast": {"languages": ["go"], "severity_threshold": "high"}},
        )
        content = plan.changes[0].content or ""
        assert '["go"]' in content
        assert "severity-threshold: high" in content

    async def test_github_actions_expressions_survive_rendering(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding
    ) -> None:
        """Jinja's default {{ }} would eat every ${{ }} in the workflow. The
        delimiters are remapped to << >> precisely so this holds."""
        plan = await installer.plan(onboarding, {"sast"})
        content = plan.changes[0].content or ""
        assert "${{ github.ref }}" in content
        assert "${{ matrix.language }}" in content


class TestPathCollision:
    async def test_a_human_written_file_at_our_path_aborts(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding, github: FakeGitHubClient
    ) -> None:
        """spec 03 §8: abort with a clear error rather than silently
        overwriting someone's workflow."""
        github.repos[REPO].branches["main"][SAST_PATH] = "name: Someone's CodeQL setup"

        with pytest.raises(PathCollisionError) as excinfo:
            await installer.plan(onboarding, {"sast"})

        assert SAST_PATH in str(excinfo.value)
        assert "did not generate" in str(excinfo.value)

    async def test_our_own_previous_file_is_not_a_collision(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding, github: FakeGitHubClient
    ) -> None:
        """A resync must be able to update the file it wrote last time."""
        github.repos[REPO].branches["main"][SAST_PATH] = (
            f"# {GENERATED_MARKER} - template version: 0.9.0\nname: old\n"
        )
        plan = await installer.plan(onboarding, {"sast"})
        assert plan.added == ["sast"]

    async def test_collision_check_happens_before_anything_is_written(
        self, installer: WorkflowInstaller, onboarding: RepoOnboarding, github: FakeGitHubClient
    ) -> None:
        github.repos[REPO].branches["main"][SAST_PATH] = "name: mine"
        with pytest.raises(PathCollisionError):
            await installer.plan(onboarding, {"sast"})

        assert not any(call[0] == "create_branch" for call in github.calls)
        assert not any(call[0] == "put_actions_secret" for call in github.calls)


class TestApply:
    async def test_opens_a_pull_request_with_the_workflow(
        self, installer, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        result = await install(installer, session, onboarding, registry, {"sast"})

        assert result.pull_request is not None
        assert result.branch is not None and result.branch.startswith(BRANCH_PREFIX)
        assert SAST_PATH in github.repos[REPO].branches[result.branch]

    async def test_provisions_the_ingestion_secret_once(
        self, multi, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        first = await install(multi, session, onboarding, registry, {"sast"})
        assert first.secret_provisioned
        assert DEFAULT_SECRET_NAME in github.repos[REPO].secrets

        onboarding.enabled_capabilities = ["sast"]
        second = await install(multi, session, onboarding, registry, {"sast", "secrets"})
        assert not second.secret_provisioned, (
            "re-issuing would rotate a working credential every time an admin "
            "ticks a box (D-009)"
        )

    async def test_the_stored_secret_is_ciphertext(
        self, installer, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        """spec 03 §4a: a plaintext token never crosses the wire."""
        await install(installer, session, onboarding, registry, {"sast"})
        stored = github.repos[REPO].secrets[DEFAULT_SECRET_NAME]
        token = registry.list_tokens()[0]
        assert stored != token.token_sha256
        assert len(stored) > 40

    async def test_grants_are_applied_immediately_not_on_merge(
        self, installer, session, onboarding, registry
    ) -> None:
        """spec 03 §5: ingestion is live before the PR merges, so a workflow
        merged from it can post results straight away."""
        result = await install(installer, session, onboarding, registry, {"sast"})
        assert result.grants_added == {"sast"}
        assert registry.granted_capabilities(REPO) == {"sast"}

    async def test_disabling_revokes_the_grant_without_waiting_for_merge(
        self, installer, session, onboarding, registry
    ) -> None:
        """An unmerged removal PR must not leave a capability writing for days."""
        await install(installer, session, onboarding, registry, {"sast"})
        onboarding.enabled_capabilities = ["sast"]

        result = await install(installer, session, onboarding, registry, set())

        assert result.grants_removed == {"sast"}
        assert registry.granted_capabilities(REPO) == set()

    async def test_capabilities_are_pending_until_merge(
        self, installer, session, onboarding, registry
    ) -> None:
        """The dashboard must not claim coverage that has not shipped."""
        await install(installer, session, onboarding, registry, {"sast"})
        assert onboarding.enabled_capabilities == []
        assert onboarding.pending_capabilities == ["sast"]
        assert onboarding.pending_pr_number is not None

    async def test_an_install_event_is_recorded(
        self, installer, session, onboarding, registry
    ) -> None:
        result = await install(installer, session, onboarding, registry, {"sast"})
        session.flush()

        event = session.query(WorkflowInstallEvent).one()
        assert event.status == "opened"
        assert event.capabilities_added == ["sast"]
        assert event.pr_number == result.pull_request.number

    async def test_noop_opens_no_pull_request(
        self, installer, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        await already_enabled(installer, github, onboarding, "sast")
        result = await install(installer, session, onboarding, registry, {"sast"})

        assert result.pull_request is None
        assert github.repos[REPO].pull_requests == []

    async def test_a_missing_merged_workflow_is_restored(
        self, installer, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        """`sast` is enabled but its file is not in the repository — somebody
        deleted it, or a merge went wrong. Re-saving the same set now opens a
        PR putting it back, where the old set-comparison called it a no-op and
        left the repo silently unscanned while the dashboard claimed coverage.
        """
        onboarding.enabled_capabilities = ["sast"]

        result = await install(installer, session, onboarding, registry, {"sast"})

        assert result.pull_request is not None
        assert result.plan.updated == ["sast"]
        assert [c.path for c in result.plan.changes] == [SAST_PATH]

    async def test_noop_still_converges_grants_and_the_secret(
        self, installer, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        """Re-saving is a repair action, not a null op.

        A repo whose workflows are merged but whose token went missing can
        never upload anything. Converging on every save means the fix is
        "press save again" rather than a support ticket.
        """
        onboarding.enabled_capabilities = ["sast"]
        assert registry.granted_capabilities(REPO) == set()

        await install(installer, session, onboarding, registry, {"sast"})

        assert registry.granted_capabilities(REPO) == {"sast"}
        assert DEFAULT_SECRET_NAME in github.repos[REPO].secrets

    async def test_withdrawing_a_pending_request_closes_its_pull_request(
        self, installer, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        """Enable, change your mind before it merges.

        Leaving the PR open would let a later merge re-enable exactly what was
        withdrawn — and until this was fixed the withdrawal did nothing at all:
        the grant stayed live and the PR stayed mergeable.
        """
        await install(installer, session, onboarding, registry, {"sast"})
        assert registry.granted_capabilities(REPO) == {"sast"}

        result = await install(installer, session, onboarding, registry, set())

        assert result.pull_request is None
        assert github.repos[REPO].pull_requests[0].state == "closed"
        assert github.repos[REPO].pull_requests[0].merged is False
        assert registry.granted_capabilities(REPO) == set()
        assert onboarding.pending_capabilities is None
        assert onboarding.pending_pr_number is None

    async def test_pr_body_explains_the_change_and_the_branch_protection_trap(
        self, multi, session, onboarding, registry
    ) -> None:
        """spec 03 §8: the chicken-and-egg on a new required check is the
        maintainer's to resolve, so the PR has to say so."""
        plan = await multi.plan(onboarding, {"sast", "secrets"})
        body = multi._pr_body(plan)

        assert "branch protection" in body.lower()
        assert "generated" in body.lower()
        assert "Enable `sast`" in body
        assert "Enable `secrets`" in body


class TestIdempotency:
    async def test_a_second_request_updates_the_open_pr(
        self, multi, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        """spec 03 §4: never a second PR while one is open."""
        first = await install(multi, session, onboarding, registry, {"sast"})
        second = await install(multi, session, onboarding, registry, {"sast", "secrets"})

        assert len(github.repos[REPO].pull_requests) == 1
        assert second.pull_request is not None and first.pull_request is not None
        assert second.pull_request.number == first.pull_request.number
        assert second.branch == first.branch

    async def test_the_updated_pr_carries_the_recomputed_diff(
        self, multi, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        await install(multi, session, onboarding, registry, {"sast"})
        result = await install(multi, session, onboarding, registry, {"sast", "secrets"})

        assert result.branch is not None
        tree = github.repos[REPO].branches[result.branch]
        assert SAST_PATH in tree
        assert SECRETS_PATH in tree

    async def test_the_second_event_is_marked_as_an_update(
        self, multi, session, onboarding, registry
    ) -> None:
        await install(multi, session, onboarding, registry, {"sast"})
        await install(multi, session, onboarding, registry, {"sast", "secrets"})
        session.flush()

        statuses = [e.status for e in session.query(WorkflowInstallEvent).all()]
        assert statuses == ["opened", "updated"]


class TestMerge:
    async def test_merging_promotes_pending_to_active(
        self, installer, session, onboarding, registry
    ) -> None:
        """spec 03 §3.6 — the only place enabled_capabilities changes."""
        result = await install(installer, session, onboarding, registry, {"sast"})
        assert result.pull_request is not None

        promoted = WorkflowInstaller.on_install_pr_merged(
            session, onboarding, result.pull_request.number
        )

        assert promoted
        assert onboarding.enabled_capabilities == ["sast"]
        assert onboarding.pending_capabilities is None
        assert onboarding.pending_pr_number is None
        assert onboarding.status == "active"

    async def test_merging_an_unrelated_pr_changes_nothing(
        self, installer, session, onboarding, registry
    ) -> None:
        await install(installer, session, onboarding, registry, {"sast"})

        assert not WorkflowInstaller.on_install_pr_merged(session, onboarding, 9999)
        assert onboarding.enabled_capabilities == []
        assert onboarding.status == "pending_install"

    async def test_merge_marks_the_install_event(
        self, installer, session, onboarding, registry
    ) -> None:
        result = await install(installer, session, onboarding, registry, {"sast"})
        session.flush()
        WorkflowInstaller.on_install_pr_merged(
            session, onboarding, result.pull_request.number
        )
        session.flush()

        event = session.query(WorkflowInstallEvent).one()
        assert event.status == "merged"
        assert event.merged_at is not None

    async def test_a_second_change_after_merge_opens_a_fresh_pr(
        self, multi, session, onboarding, registry, github: FakeGitHubClient
    ) -> None:
        first = await install(multi, session, onboarding, registry, {"sast"})
        github.repos[REPO].pull_requests[0].state = "closed"
        WorkflowInstaller.on_install_pr_merged(
            session, onboarding, first.pull_request.number
        )

        second = await install(multi, session, onboarding, registry, {"sast", "secrets"})

        assert len(github.repos[REPO].pull_requests) == 2
        assert second.plan.added == ["secrets"]
        assert second.plan.removed == []


class TestGateOrdering:
    """`workflow_run` triggers, which are silently wrong when they are wrong.

    A gate naming a workflow that does not exist simply never fires; a gate
    naming itself is a workflow triggering on its own completion. Neither
    produces an error anywhere — the capability just stops working.
    """

    def test_a_gate_never_waits_for_itself(self) -> None:
        from mykronos.installer.installer import _gate_depends_on

        assert "Mykronos patchwork" not in _gate_depends_on(
            "patchwork", ["sast", "patchwork", "oracle"]
        )
        assert "Mykronos oracle" not in _gate_depends_on(
            "oracle", ["sast", "patchwork", "oracle"]
        )

    def test_oracle_waits_for_patchwork(self) -> None:
        """Oracle discounts findings with a fix in flight (spec 08 §9). If
        they both trigger on the scanners they race, and Oracle scores before
        the draft pull requests exist — so the discount is missing from
        exactly the decision somebody is reading."""
        from mykronos.installer.installer import _gate_depends_on

        assert _gate_depends_on("oracle", ["sast", "patchwork", "oracle"]) == [
            "Mykronos sast",
            "Mykronos patchwork",
        ]

    def test_patchwork_waits_only_for_scanners(self) -> None:
        from mykronos.installer.installer import _gate_depends_on

        assert _gate_depends_on("patchwork", ["sast", "secrets", "patchwork"]) == [
            "Mykronos sast",
            "Mykronos secrets",
        ]

    def test_a_capability_that_is_not_enabled_is_not_waited_for(self) -> None:
        """A trigger naming a workflow that does not exist never fires."""
        from mykronos.installer.installer import _gate_depends_on

        assert _gate_depends_on("oracle", ["sast", "oracle"]) == ["Mykronos sast"]

    def test_a_scanner_waits_for_nothing(self) -> None:
        from mykronos.installer.installer import _gate_depends_on

        assert _gate_depends_on("sast", ["sast", "oracle"]) == []
