/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ingest/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Called by a workflow before scanning so it can fail fast (spec 05 §4).
         *
         *     Reports whether the lake is actually writable rather than merely whether
         *     the process is up — an unwritable disk is the failure this exists to catch.
         */
        get: operations["health_api_ingest_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/scan-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Scan Run
         * @description Register or finalise a ScanRun.
         *
         *     Posted once at workflow start and again at completion with
         *     `completed_at`/`scan_status`/`finding_count`; the second post upserts onto
         *     the first by `scan_run_id` (docs/DECISIONS.md D-002).
         *
         *     Every run is registered — success, no-op and failure alike — so scan
         *     coverage and freshness are auditable from the lake alone (spec 04 §7).
         */
        post: operations["ingest_scan_run_api_ingest_scan_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Findings
         * @description Submit a batch of normalized findings for a scan run.
         *
         *     An empty batch is valid and meaningful: it is how a scanner reports
         *     "I ran and found nothing," which the lake must be able to tell apart from
         *     "never ran" (spec 04 §6).
         */
        post: operations["ingest_findings_api_ingest_findings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Raw Output
         * @description Archive a scanner's original, unmodified output (spec 05 §7).
         *
         *     Kept alongside the normalized findings so a disputed result can always be
         *     traced back to exactly what the tool said, rather than to our
         *     interpretation of it. Retention is bounded separately; normalized
         *     `Finding` rows outlive the raw files.
         */
        post: operations["ingest_raw_output_api_ingest_raw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{capability}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Capability Payload
         * @description Capability-specific tables: InsiderRiskSignal, SscsEvidence,
         *     RemediationEvent, RiskDecision.
         *
         *     Declared here because spec 05 §4 defines the route, but the target tables
         *     arrive with their capabilities in Phases 3-6. Returning 501 rather than 404
         *     keeps the contract visible instead of looking like a routing bug.
         */
        post: operations["ingest_capability_payload_api_ingest__capability__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio
         * @description The landing page (spec 10 §2.1).
         */
        get: operations["portfolio_api_dashboard_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/repos/{repo_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Repo Findings
         * @description Filterable finding list for one repo (spec 10 §2.2).
         */
        get: operations["repo_findings_api_dashboard_repos__repo_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/repos/{repo_id}/scan-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Health
         * @description Per-capability run history and freshness (spec 10 §2.2).
         *
         *     Auditable from the lake alone, which is the point of writing a ScanRun for
         *     every run including the ones that found nothing (spec 04 §7).
         */
        get: operations["scan_health_api_dashboard_repos__repo_id__scan_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/findings/{finding_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Finding Status
         * @description Record a human disposition (spec 10 §2.2).
         *
         *     Admin-only: this changes what Oracle will decide, so it is a write, not a
         *     view. Viewers can read every finding and change none of them.
         */
        patch: operations["set_finding_status_api_dashboard_findings__finding_id__status_patch"];
        trace?: never;
    };
    "/api/repos/-/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Capability Schemas
         * @description Config schema per capability, for the UI to render a form from.
         *
         *     Under `/-/` so it cannot be mistaken for a repo id. The valid tool list in
         *     each schema comes from the adapter registry rather than being restated
         *     here, so the form can never offer a tool the platform cannot parse.
         */
        get: operations["list_capability_schemas_api_repos___capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repos */
        get: operations["list_repos_api_repos_get"];
        put?: never;
        /**
         * Onboard Repo
         * @description Idempotently register a repo (spec 02 §7).
         *
         *     Usually the `installation` webhook gets here first; this exists for the
         *     manual path and for re-registering after an offboard. Either way it
         *     upserts, so the two paths cannot produce duplicate rows.
         */
        post: operations["onboard_repo_api_repos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repo */
        get: operations["get_repo_api_repos__repo_id__get"];
        put?: never;
        post?: never;
        /**
         * Offboard Repo
         * @description Offboard a repo (spec 02 §6).
         *
         *     Stops all scheduled activity and revokes every ingestion token and grant,
         *     but **does not delete historical data lake rows** — those are the audit
         *     trail. Deleting them is a separate, explicitly-confirmed action.
         */
        delete: operations["offboard_repo_api_repos__repo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Capabilities
         * @description Set the enabled capability set and open the workflow-install PR.
         *
         *     Capability *validation* happens here rather than at workflow run time
         *     (spec 04 §7): a bad tool name should fail the save, not surface three
         *     hours later as a red pipeline nobody connects to this action.
         */
        patch: operations["update_capabilities_api_repos__repo_id__capabilities_patch"];
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Github Webhook */
        post: operations["github_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unauthenticated liveness probe
         * @description For infrastructure only. Deliberately reveals nothing about the
         *     lake — the authenticated /api/ingest/health is what workflows call.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Capability
         * @enum {string}
         */
        Capability: "sast" | "dast" | "secrets" | "containers" | "iac" | "cloud" | "aegis" | "atlas" | "patchwork" | "oracle";
        /** CapabilityStateOut */
        CapabilityStateOut: {
            /** Capability */
            capability: string;
            /** Has Scanned */
            has_scanned: boolean;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Last Scan Status */
            last_scan_status?: string | null;
            /**
             * Open Findings
             * @default 0
             */
            open_findings: number;
        };
        /** CapabilityUpdate */
        CapabilityUpdate: {
            /** Capabilities */
            capabilities: components["schemas"]["Capability"][];
            /** Config */
            config?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** CapabilityUpdateResult */
        CapabilityUpdateResult: {
            repo: components["schemas"]["RepoSummary"];
            /** Added */
            added: string[];
            /** Removed */
            removed: string[];
            /** Pull Request Url */
            pull_request_url?: string | null;
            /** Pull Request Number */
            pull_request_number?: number | null;
            /**
             * Secret Provisioned
             * @default false
             */
            secret_provisioned: boolean;
            /** Detail */
            detail: string;
        };
        /**
         * FindingBatch
         * @description A batch of findings for one scan run.
         *
         *     `max_length` here is the spec 05 §6 backpressure ceiling; exceeding it is a
         *     422 from Pydantic rather than a partial ingest.
         *
         *     Note what is and is not a field. `capability` must be declared, because one
         *     token now spans several capabilities (D-009) — the server checks it against
         *     the token's grant set. `repo_full_name` is *not* a field and never will be:
         *     it comes from the token, so there is nowhere to name another repo.
         */
        FindingBatch: {
            /** Scan Run Id */
            scan_run_id: string;
            capability: components["schemas"]["Capability"];
            /** Findings */
            findings?: components["schemas"]["FindingSubmission"][];
        };
        /**
         * FindingOut
         * @description One finding as the dashboard serves it.
         *
         *     Modelled rather than passed through as a bare dict so the OpenAPI schema —
         *     and therefore the generated TypeScript — describes the real shape. A
         *     `dict[str, Any]` response types the whole frontend as `unknown` and pushes
         *     the guessing into a cast.
         *
         *     `code_snippet` and `raw_finding_json` are null for viewer roles rather than
         *     absent. The security property is that the *value* is not transmitted
         *     (spec 12 §5); a stable key shape costs nothing and spares every caller an
         *     optional-property dance.
         */
        FindingOut: {
            /** Finding Id */
            finding_id: string;
            /** Capability */
            capability: string;
            /** Rule Id */
            rule_id: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            severity: components["schemas"]["Severity"];
            /** Cvss Score */
            cvss_score?: number | null;
            /** File Path */
            file_path?: string | null;
            /** Line Start */
            line_start?: number | null;
            /** Line End */
            line_end?: number | null;
            /** Symbol */
            symbol?: string | null;
            /** Package Name */
            package_name?: string | null;
            /** Package Version */
            package_version?: string | null;
            /** Status */
            status: string;
            /** Fingerprint Version */
            fingerprint_version?: string | null;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Code Snippet */
            code_snippet?: string | null;
            /** Raw Finding Json */
            raw_finding_json?: unknown;
        };
        /**
         * FindingStatus
         * @enum {string}
         */
        FindingStatus: "open" | "fixed" | "false_positive" | "accepted_risk" | "suppressed";
        /**
         * FindingSubmission
         * @description One normalized finding as produced by an adapter (spec 04 §4).
         *
         *     Note the absence of `finding_id`, `status`, and the `first_seen`/
         *     `last_seen` fields: those are the server's to assign. An adapter that
         *     could name its own finding_id could silently fork or merge identities.
         */
        FindingSubmission: {
            /** Rule Id */
            rule_id: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            severity: components["schemas"]["Severity"];
            /** Cvss Score */
            cvss_score?: number | null;
            /** File Path */
            file_path?: string | null;
            /** Line Start */
            line_start?: number | null;
            /** Line End */
            line_end?: number | null;
            /**
             * Symbol
             * @description Enclosing function/class/resource. Part of the fingerprint.
             */
            symbol?: string | null;
            /**
             * Code Snippet
             * @description Source at the finding location, captured while the repo is checked out. Normalized and hashed into finding_id (spec 05 §5). Supplying this is what keeps the finding stable across unrelated edits.
             */
            code_snippet?: string | null;
            /** Package Name */
            package_name?: string | null;
            /** Package Version */
            package_version?: string | null;
            /**
             * Raw Finding Json
             * @description Original tool record, preserved verbatim (spec 05 §3).
             */
            raw_finding_json?: {
                [key: string]: unknown;
            };
        };
        /** FindingsPage */
        FindingsPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /**
             * Raw Output Included
             * @description False for viewer roles; raw output is admin-only (spec 12 §5).
             */
            raw_output_included: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Datalake Writable */
            datalake_writable: boolean;
            /** Buffered Segments */
            buffered_segments: number;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Repo Full Name
             * @default
             */
            repo_full_name: string;
            /** Granted Capabilities */
            granted_capabilities?: string[];
        };
        /**
         * IngestAccepted
         * @description A 200 from an ingestion endpoint is a durability guarantee (spec 05 §4).
         */
        IngestAccepted: {
            /** Accepted */
            accepted: number;
            /** Scan Run Id */
            scan_run_id?: string | null;
            /**
             * Buffered At
             * Format: date-time
             */
            buffered_at?: string;
            /**
             * Detail
             * @default Written to the durability buffer.
             */
            detail: string;
        };
        /** OnboardRequest */
        OnboardRequest: {
            /** Github Repo Full Name */
            github_repo_full_name: string;
            /** Github Installation Id */
            github_installation_id: number;
            /**
             * Default Branch
             * @default main
             */
            default_branch: string;
            /**
             * Org Login
             * @default
             */
            org_login: string;
        };
        /** PortfolioOut */
        PortfolioOut: {
            summary: components["schemas"]["PortfolioSummary"];
            /** Repos */
            repos: components["schemas"]["PortfolioRowOut"][];
        };
        /** PortfolioRowOut */
        PortfolioRowOut: {
            /** Repo Id */
            repo_id: string;
            /** Repo Full Name */
            repo_full_name: string;
            /** Status */
            status: string;
            /** Enabled Capabilities */
            enabled_capabilities: string[];
            /** Pending Capabilities */
            pending_capabilities: string[] | null;
            /** Severity Counts */
            severity_counts: {
                [key: string]: number;
            };
            /** Total Open */
            total_open: number;
            /** Last Scan At */
            last_scan_at: string | null;
            /** Awaiting First Scan */
            awaiting_first_scan: boolean;
            /** Is Stale */
            is_stale: boolean;
            /** Capability States */
            capability_states: components["schemas"]["CapabilityStateOut"][];
            /**
             * Risk Score
             * @description Oracle's score. Null until Phase 3 — deliberately not 0, which would read as 'assessed, no risk' rather than 'not assessed'.
             */
            risk_score?: number | null;
            /** Recommendation */
            recommendation?: string | null;
        };
        /**
         * PortfolioSummary
         * @description The cards above the table (spec 10 §2.1).
         */
        PortfolioSummary: {
            /**
             * Active Repos
             * @default 0
             */
            active_repos: number;
            /**
             * Open Critical
             * @default 0
             */
            open_critical: number;
            /**
             * Open High
             * @default 0
             */
            open_high: number;
            /**
             * Repos Awaiting First Scan
             * @default 0
             */
            repos_awaiting_first_scan: number;
            /**
             * Repos With Stale Scans
             * @default 0
             */
            repos_with_stale_scans: number;
            /**
             * Repos No Go
             * @default 0
             */
            repos_no_go: number;
        };
        /**
         * RawAccepted
         * @description Archived raw tool output (spec 05 §7).
         */
        RawAccepted: {
            /** Raw Output Ref */
            raw_output_ref: string;
            /** Bytes Written */
            bytes_written: number;
        };
        /** RepoDetail */
        RepoDetail: {
            /** Id */
            id: string;
            /** Github Repo Full Name */
            github_repo_full_name: string;
            /** Status */
            status: string;
            /** Enabled Capabilities */
            enabled_capabilities: string[];
            /** Pending Capabilities */
            pending_capabilities: string[] | null;
            /** Pending Pr Number */
            pending_pr_number: number | null;
            /** Default Branch */
            default_branch: string;
            /**
             * Onboarded At
             * Format: date-time
             */
            onboarded_at: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Github Installation Id */
            github_installation_id: number;
            /** Onboarded By */
            onboarded_by: string;
            /** Auto Merge Workflow Prs */
            auto_merge_workflow_prs: boolean;
            /** Granted Capabilities */
            granted_capabilities: string[];
            /** Capability Config */
            capability_config: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** RepoSummary */
        RepoSummary: {
            /** Id */
            id: string;
            /** Github Repo Full Name */
            github_repo_full_name: string;
            /** Status */
            status: string;
            /** Enabled Capabilities */
            enabled_capabilities: string[];
            /** Pending Capabilities */
            pending_capabilities: string[] | null;
            /** Pending Pr Number */
            pending_pr_number: number | null;
            /** Default Branch */
            default_branch: string;
            /**
             * Onboarded At
             * Format: date-time
             */
            onboarded_at: string;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /**
         * ScanRunSubmission
         * @description POSTed at workflow start, and again at completion.
         *
         *     The client owns `scan_run_id` (it generates a UUID before scanning so the
         *     findings batch can reference it). Re-POSTing the same id updates the row
         *     rather than creating a second one — see `docs/DECISIONS.md`, D-002.
         */
        ScanRunSubmission: {
            /** Scan Run Id */
            scan_run_id: string;
            /** Repo Full Name */
            repo_full_name: string;
            capability: components["schemas"]["Capability"];
            /** Tool Name */
            tool_name: string;
            /**
             * Tool Version
             * @default
             */
            tool_version: string;
            /** Commit Sha */
            commit_sha: string;
            /** Branch */
            branch: string;
            /** Pr Number */
            pr_number?: number | null;
            triggered_by: components["schemas"]["TriggeredBy"];
            /**
             * Github Workflow Run Id
             * @default
             */
            github_workflow_run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** @default success */
            scan_status: components["schemas"]["ScanStatus"];
            /**
             * Finding Count
             * @default 0
             */
            finding_count: number;
            /** Raw Output Ref */
            raw_output_ref?: string | null;
        };
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "success" | "no_applicable_targets" | "partial_failure" | "failure";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "low" | "medium" | "high" | "critical";
        /** StatusChange */
        StatusChange: {
            status: components["schemas"]["FindingStatus"];
            /**
             * Reason
             * @description Why. spec 11 §4: a bare click with no reason is recorded but flagged low-confidence and barred from promotion, because reasons are what make a learning actionable rather than a statistic.
             * @default
             */
            reason: string;
        };
        /** StatusChangeResult */
        StatusChangeResult: {
            /** Finding Id */
            finding_id: string;
            /** Status */
            status: string;
            /** Reason Supplied */
            reason_supplied: boolean;
            /** Retro Signal */
            retro_signal: string;
        };
        /**
         * TriggeredBy
         * @enum {string}
         */
        TriggeredBy: "pull_request" | "push" | "schedule" | "workflow_dispatch" | "manual";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_ingest_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ingest_scan_run_api_ingest_scan_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRunSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_findings_api_ingest_findings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_raw_output_api_ingest_raw_post: {
        parameters: {
            query: {
                scan_run_id: string;
                capability: components["schemas"]["Capability"];
                filename: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_capability_payload_api_ingest__capability__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capability: components["schemas"]["Capability"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_dashboard_portfolio_get: {
        parameters: {
            query?: {
                include_removed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repo_findings_api_dashboard_repos__repo_id__findings_get: {
        parameters: {
            query?: {
                capability?: components["schemas"]["Capability"] | null;
                severity?: components["schemas"]["Severity"] | null;
                finding_status?: components["schemas"]["FindingStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_health_api_dashboard_repos__repo_id__scan_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_finding_status_api_dashboard_findings__finding_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_capability_schemas_api_repos___capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_repos_api_repos_get: {
        parameters: {
            query?: {
                /** @description Offboarded repos are hidden by default but remain queryable for audit (spec 10 §7). */
                include_removed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboard_repo_api_repos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repo_api_repos__repo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offboard_repo_api_repos__repo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_capabilities_api_repos__repo_id__capabilities_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapabilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-github-event"?: string | null;
                "x-hub-signature-256"?: string | null;
                "x-github-delivery"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
