<#
.SYNOPSIS
    Generate deploy/concourse/.env with fresh credentials, then bring the stack up.

.DESCRIPTION
    Every secret here is generated, never defaulted. The compose file refuses to
    start without them (`:?set it in .env`), which is deliberate: the failure
    mode of a default credential is that it works, and nobody notices.

    Re-running is safe. An existing .env is left alone unless -Rotate is given,
    so this can be used to start the stack as well as to create it.

.NOTES
    ASCII only. Windows PowerShell 5.1 reads a BOM-less file as CP1252, so a
    UTF-8 dash becomes three characters and the parser reports errors on lines
    that are not the problem.
#>

[CmdletBinding()]
param(
    [string]$EnvFile = (Join-Path $PSScriptRoot ".env"),
    [switch]$Rotate,
    [switch]$NoStart
)

$ErrorActionPreference = "Stop"

function New-Secret {
    param([int]$Bytes = 24)
    $buffer = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($buffer)
    # URL-safe: these values travel through compose interpolation and a shell.
    [Convert]::ToBase64String($buffer).Replace('+', '-').Replace('/', '_').TrimEnd('=')
}

if ((Test-Path $EnvFile) -and -not $Rotate) {
    Write-Host "Using the existing $EnvFile (pass -Rotate to replace it)." -ForegroundColor DarkGray
} else {
    if (Test-Path $EnvFile) {
        $backup = "$EnvFile.bak-$(Get-Date -Format yyyyMMdd-HHmmss)"
        Copy-Item $EnvFile $backup
        Write-Host "Backed up the previous .env to $backup" -ForegroundColor DarkGray
    }

    $lines = @(
        "# Generated by setup.ps1. Gitignored - see deploy/concourse/README.md.",
        "# Rotating these means `docker compose up -d --force-recreate`.",
        "",
        "CONCOURSE_LOCAL_USER=mykronos",
        "CONCOURSE_LOCAL_PASSWORD=$(New-Secret)",
        "CONCOURSE_POSTGRES_PASSWORD=$(New-Secret)",
        "",
        "MINIO_ROOT_USER=mykronos",
        "MINIO_ROOT_PASSWORD=$(New-Secret 32)",
        "# Point this at the NAS to keep artifacts off the local disk.",
        "# MINIO_DATA_DIR=//nas/share/concourse-artifacts",
        "",
        "# Set this to the tunnel hostname once concourse. is routed.",
        "CONCOURSE_EXTERNAL_URL=http://localhost:8080"
    )
    Set-Content -Path $EnvFile -Value $lines -Encoding UTF8
    Write-Host "Wrote $EnvFile with generated credentials." -ForegroundColor Green
}

# Persistent session signing key. Without one, quickstart generates a fresh
# key on every start, every browser cookie signed with the old one becomes
# invalid, and the login page reports "invalid state token" - which reads as
# a broken login rather than as a container restart.
#
# Only this key. Supplying the TSA host and worker keys too leaves the
# embedded worker unable to connect ("remote host public key mismatch"),
# because quickstart manages that handshake itself.
$keyDir = Join-Path $PSScriptRoot "keys"
New-Item -ItemType Directory -Force -Path $keyDir | Out-Null
if (-not (Test-Path (Join-Path $keyDir "session_signing_key"))) {
    Write-Host "Generating the session signing key..." -ForegroundColor Cyan
    docker run --rm -v "${keyDir}:/keys" concourse/concourse:7.14 generate-key -t rsa -f /keys/session_signing_key | Out-Null
}

if ($NoStart) { return }

Push-Location $PSScriptRoot
try {
    Write-Host "`nStarting the stack..." -ForegroundColor Cyan
    docker compose up -d
    if ($LASTEXITCODE -ne 0) { throw "docker compose up failed with $LASTEXITCODE" }

    Write-Host "`nWaiting for Concourse to report healthy..." -ForegroundColor Cyan
    $deadline = (Get-Date).AddMinutes(4)
    do {
        Start-Sleep -Seconds 10
        $state = (docker inspect -f '{{.State.Health.Status}}' mykronos-concourse 2>$null)
        Write-Host "  $state"
        if ($state -eq "healthy") { break }
    } while ((Get-Date) -lt $deadline)

    if ($state -ne "healthy") {
        throw "Concourse did not become healthy. Check: docker compose logs concourse"
    }

    $user = (Select-String -Path $EnvFile -Pattern '^CONCOURSE_LOCAL_USER=').Line.Split('=', 2)[1]
    Write-Host "`nConcourse is up on http://localhost:8080" -ForegroundColor Green
    Write-Host "  user: $user"
    Write-Host "  password: in $EnvFile (not printed here)"
    Write-Host "`nNext: .\set-pipeline.ps1" -ForegroundColor Cyan
} finally {
    Pop-Location
}
