"""Did the fix actually work? (spec 25 §1, §2)

Patchwork has opened pull requests since spec 08 and has never been able to
say whether any of them removed a vulnerability. The merge is observed — the
webhook records `pr_status = merged` — and then nothing re-scans, nothing
links the merge to the finding closing, and `mean_time_to_fix` stays a
repository-level number that cannot be attributed to a route. So the platform
could report that it opened pull requests, and not that it reduced risk.

**Two phases, because they answer at different times.**

*Dispatch* happens once, shortly after the merge: scan the merge commit, for
the one capability that produced the finding and no other. A full fifteen-check
re-run on every fix merge is a cost this platform explicitly cannot afford at
the cadence merges happen (D-053 is the precedent, and DAST is cheaper than
that would be).

*Resolution* happens whenever the verifying scan lands, which may be minutes
or hours later and may never happen at all. It is deliberately not inferred
from a timer: the resolver waits for evidence and, failing that, says
`not_scanned` rather than guessing.

**Why the join is on the commit, not on a run id.** The scan run's identity is
generated by the runner, so this platform cannot know it in advance; and the
runner reports its own `triggered_by`, so a "verification" label would need a
pipeline change in every repository. The merge commit is the one fact both
sides already hold. A successful run for (repo, capability, commit) is the
verifying run.

**Why the verdict reads the run and not the finding's status.** A finding is
not marked `fixed` until it has been absent from *two* consecutive scans
(`reconcile.REQUIRED_ABSENCES`) — flap protection, which exists to stop a
finding's `resolved_at` churning, and which is a different question from the
one asked here. Waiting for it would mean a verification could not conclude
until an unrelated second scan happened to run, and would report a working fix
as unverified in the meantime.

So the evidence is the verifying run itself: it succeeded, and it either
re-reported this finding (`last_seen_scan_run_id` points at it — genuinely
still there) or it did not (gone from the code as of that commit). The
finding's status stays the platform's own conservative business; this column
says what one scan of one commit actually observed.

Only a `success` run gives a verdict. A `partial_failure` may not have scanned
the file in question, so the absence of a finding proves nothing — that is
`inconclusive`, and saying so is the whole reason the outcome exists.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import timedelta
from typing import Any

from mykronos.lake.buffer import WriteAheadBuffer
from mykronos.lake.catalog import Catalog
from mykronos.schemas import utcnow

logger = logging.getLogger(__name__)

#: How long to wait for a verifying scan before calling it `not_scanned`.
#:
#: Generous on purpose. A repository whose pipeline runs nightly, or whose
#: worker was busy, has not failed to verify — it has not verified *yet*, and
#: a verdict that arrives late is worth more than one that arrives wrong.
VERIFICATION_DEADLINE = timedelta(hours=36)

#: Outcomes. `pending` is a real stored state rather than a null, so "waiting
#: for evidence" and "nobody ever asked" are distinguishable in the lake.
PENDING = "pending"
VERIFIED_FIXED = "verified_fixed"
STILL_OPEN = "still_open"
NOT_SCANNED = "not_scanned"
INCONCLUSIVE = "inconclusive"


@dataclass
class VerificationResult:
    """What one pass over the pending verifications changed."""

    dispatched: int = 0
    dispatch_failed: int = 0
    verified_fixed: int = 0
    still_open: int = 0
    not_scanned: int = 0
    inconclusive: int = 0
    waiting: int = 0

    def summary(self) -> str:
        return (
            f"{self.dispatched} dispatched, {self.verified_fixed} verified fixed, "
            f"{self.still_open} still open, {self.not_scanned} not scanned, "
            f"{self.inconclusive} inconclusive, {self.waiting} waiting"
        )


def _event_rows(catalog: Catalog, outcome: str) -> list[dict[str, Any]]:
    if not catalog.all_files("remediation_events"):
        return []
    rows = catalog.query(
        """
        SELECT event_id, repo_full_name, finding_id, fix_pr_number, rationale,
               pipeline_stage_reached, triage_classification, pr_status,
               verification_commit_sha, verification_dispatched_at, created_at
        FROM remediation_events
        WHERE verification_outcome = ? AND pr_status = 'merged'
        """,
        [outcome],
    )
    names = (
        "event_id",
        "repo_full_name",
        "finding_id",
        "fix_pr_number",
        "rationale",
        "pipeline_stage_reached",
        "triage_classification",
        "pr_status",
        "verification_commit_sha",
        "verification_dispatched_at",
        "created_at",
    )
    return [dict(zip(names, row, strict=True)) for row in rows]


def _write(buffer: WriteAheadBuffer, event: dict[str, Any], **changes: Any) -> None:
    """Append one event row, carrying forward what this writer does not own.

    The non-coalescing columns — rationale, stage, classification — are
    re-read and written back rather than left null, because compaction
    refreshes those from the incoming row and a null would blank them. Same
    shape `record_pr_outcome` already uses.
    """
    row: dict[str, Any] = {
        "event_id": event["event_id"],
        "repo_full_name": event["repo_full_name"],
        "finding_id": event["finding_id"],
        "toxic_combination_id": None,
        "contributing_finding_ids": json.dumps([]),
        "pipeline_stage_reached": event["pipeline_stage_reached"],
        "triage_classification": event["triage_classification"],
        "fix_pr_number": event["fix_pr_number"],
        "fix_pr_url": None,
        "pr_status": event["pr_status"],
        "rationale": event["rationale"],
        "verification_commit_sha": None,
        "verification_dispatched_at": None,
        "verification_scan_run_id": None,
        "verification_outcome": None,
        "verified_at": None,
        "time_to_verified_seconds": None,
        "created_at": event.get("created_at") or utcnow(),
        "updated_at": utcnow(),
    }
    row.update(changes)
    buffer.append("remediation_events", [row])


def _capability_of(catalog: Catalog, finding_id: str) -> str | None:
    rows = catalog.query(
        "SELECT capability FROM findings WHERE finding_id = ? LIMIT 1", [finding_id]
    )
    return str(rows[0][0]) if rows else None


async def dispatch_pending(
    catalog: Catalog,
    buffer: WriteAheadBuffer,
    *,
    dispatch: Any,
    result: VerificationResult | None = None,
) -> VerificationResult:
    """Scan the merge commit of every fix that has just landed.

    `dispatch` is an awaitable `(repo_full_name, capability) -> bool` supplied
    by the caller — the job wires it to the same Actions/Concourse split
    `scan_now` uses, and a test supplies a recording stub. Keeping it out of
    here is what lets this module be about *what to verify* rather than about
    two dispatch mechanisms.
    """
    result = result or VerificationResult()
    for event in _event_rows(catalog, PENDING):
        if event["verification_dispatched_at"] is not None:
            continue
        if not event["verification_commit_sha"]:
            # Merged with no merge commit reported — a squash into a protected
            # branch can look like this. Nothing to scan against, and saying so
            # is better than scanning the branch head and attributing whatever
            # it finds to this fix.
            _write(
                buffer,
                event,
                verification_outcome=NOT_SCANNED,
                verified_at=utcnow(),
            )
            result.not_scanned += 1
            continue

        capability = _capability_of(catalog, str(event["finding_id"]))
        if capability is None:
            _write(buffer, event, verification_outcome=INCONCLUSIVE, verified_at=utcnow())
            result.inconclusive += 1
            continue

        ok = await dispatch(str(event["repo_full_name"]), capability)
        if ok:
            _write(buffer, event, verification_dispatched_at=utcnow())
            result.dispatched += 1
        else:
            result.dispatch_failed += 1
            logger.warning(
                "Could not dispatch verification for %s (%s)",
                event["event_id"],
                capability,
            )
    return result


def resolve_pending(
    catalog: Catalog,
    buffer: WriteAheadBuffer,
    *,
    result: VerificationResult | None = None,
    now: Any = None,
) -> VerificationResult:
    """Turn dispatched verifications into verdicts, where the evidence is in."""
    result = result or VerificationResult()
    moment = now or utcnow()

    for event in _event_rows(catalog, PENDING):
        dispatched_at = event["verification_dispatched_at"]
        if dispatched_at is None:
            continue

        finding_id = str(event["finding_id"])
        commit = str(event["verification_commit_sha"])
        capability = _capability_of(catalog, finding_id)
        if capability is None:
            _write(buffer, event, verification_outcome=INCONCLUSIVE, verified_at=moment)
            result.inconclusive += 1
            continue

        runs = catalog.query(
            """
            SELECT scan_run_id, scan_status
            FROM scan_runs
            WHERE repo_full_name = ? AND capability = ? AND commit_sha = ?
            ORDER BY started_at DESC
            LIMIT 1
            """,
            [event["repo_full_name"], capability, commit],
        )

        if not runs:
            if moment - dispatched_at >= VERIFICATION_DEADLINE:
                _write(buffer, event, verification_outcome=NOT_SCANNED, verified_at=moment)
                result.not_scanned += 1
            else:
                result.waiting += 1
            continue

        scan_run_id, scan_status = str(runs[0][0]), str(runs[0][1])
        if scan_status != "success":
            # A scan that failed, partly failed, or had nothing to look at has
            # not established anything about this fix. A partial failure is
            # the subtle one: the file this finding lives in may be exactly
            # the target that did not get scanned.
            _write(
                buffer,
                event,
                verification_scan_run_id=scan_run_id,
                verification_outcome=INCONCLUSIVE,
                verified_at=moment,
            )
            result.inconclusive += 1
            continue

        rows = catalog.query(
            "SELECT status, last_seen_scan_run_id, resolved_at FROM findings "
            "WHERE finding_id = ? LIMIT 1",
            [finding_id],
        )
        if not rows:
            # The finding is gone from the lake entirely — a retention purge,
            # or a repository offboarded between the merge and now. Not a fix
            # this platform can claim.
            _write(
                buffer,
                event,
                verification_scan_run_id=scan_run_id,
                verification_outcome=INCONCLUSIVE,
                verified_at=moment,
            )
            result.inconclusive += 1
            continue

        _status, last_seen_run, _resolved_at = rows[0]
        elapsed = int((moment - dispatched_at).total_seconds())
        re_reported = str(last_seen_run or "") == scan_run_id

        _write(
            buffer,
            event,
            verification_scan_run_id=scan_run_id,
            verification_outcome=STILL_OPEN if re_reported else VERIFIED_FIXED,
            verified_at=moment,
            time_to_verified_seconds=elapsed,
        )
        if re_reported:
            result.still_open += 1
        else:
            result.verified_fixed += 1

    if result.summary() and any(
        (
            result.verified_fixed,
            result.still_open,
            result.not_scanned,
            result.inconclusive,
        )
    ):
        logger.info("Fix verification: %s", result.summary())
    return result
